require("core.options")
require("core.keymaps")
require("core.autocmds")
require("lazy_setup")

require("current-theme")
require("core.lsp").setup()
require("core.lualine").setup()
require("core.which_key")
require("core.bufferline")
